import Head from "next/head";
import Link from "next/link";

export default function SignIn({ signIn, signOut, session }) {
  if (session) {
    return (
      <div>
        <Head>
          <title>AA | Stock App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="p-5">
          <nav className="flex items-center justify-between max-w-7xl mx-auto">
            <h1 className=" text-3xl font-bold">Stock App</h1>
            Signed in as {session.user.email} <br />
            {/* <img src={session.user.image} alt="profile" /> */}
            <button className="bg-gray-400 px-4 rounded py-2" onClick={signOut}>
              Sign out
            </button>
          </nav>
        </main>

        <Link href="/dashboard">
          <a className="bg-blue-500 p-4 text-white">Dashboard</a>
        </Link>
      </div>
    );
  }
  return (
    <div className="flex flex-col items-center">
      <p className="font-mono text-xl">Not signed in</p>
      <button
        className="px-3 py-2 bg-red-500 text-gray-700 rounded mt-4"
        onClick={signIn}
      >
        Sign in
      </button>
    </div>
  );
}
