import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";
import Link from "next/link";
import SignIn from "../components/SignIn";
import useSWR from "swr";

export default function Home() {
  const { data: session } = useSession();

  const fetcher = (...args) => fetch(...args).then((res) => res.json());

  const { data, error } = useSWR("/api/user", fetcher);
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  console.log(data);

  if (session) {
    return (
      <div>
        <Head>
          <title>AA | Stock App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="p-5">
          <nav className="flex items-center justify-between max-w-7xl mx-auto">
            <h1 className=" text-3xl font-bold">Stock App</h1>
            Signed in as {session.user.email} <br />
            {/* <img src={session.user.image} alt="profile" /> */}
            <button className="bg-gray-400 px-4 rounded py-2" onClick={signOut}>
              Sign out
            </button>
          </nav>
        </main>
        <ul>
          {data.map((user) => (
            <li key={user.id}>{user.email}</li>
          ))}
        </ul>
      </div>
    );
  }

  return (
    <div className="flex w-full h-screen items-center justify-center">
      <SignIn signIn={signIn} />
    </div>
  );
}
