import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";

export default function Home() {
  const { data: session } = useSession();

  console.log(session);

  if (session) {
    return (
      <div>
        <Head>
          <title>AA | Stock App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="p-5">
          <nav className='flex items-center justify-between max-w-7xl mx-auto'>
            <h1 className=" text-3xl font-bold">Stock App</h1>
            Signed in as {session.user.email} <br />
            {/* <img src={session.user.image} alt="profile" /> */}
            <button
              className="bg-gray-400 px-4 rounded py-2"
              onClick={() => signOut()}
            >
              Sign out
            </button>
          </nav>
        </main>
      </div>
    );
  }

  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
}
